# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2056177446812a5b2487d82cbdce6d69635a69263ceb3e6c34695045bba5363144a09ae45646b02a0e71506571ccd152f3b468f85674a7f28c8fc18a705b825a

test:
  secret_key_base: 310bea39b9df11a3edf23d21aae71e71364871db4b863d14223b2f2ae100a2f88b5854063d47705a406217daab6b73f4ff2143a163f08adb8a0679ad3d166dbe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
